### ISSUE TITLE
Hosts shouldn't remove on Vagrant reload

### ISSUE THREAD

**Issue by ChrisWiegman** [10up/vagrant-ghost#1]
Having hosts automatically refresh on Vagrant reload is somewhat troublesome and, seemingly, unnecessary. Would it not make more sense to, instead, simply update them on the subsequent vagrant up and not automatically remove them on the halt? I would be more than happy to test this if you're interested in PRs on this one.

**Comment by ericmann** [comment]
Since reload effectively fires halt/up, and we bind a removal to halt and adding to up, I'm not sure what the best approach here would be. More than open to seeing a proof of concept, though.

i.e. If you can find a way to update things atomically, I'm more than open to replacing the current logic within the reload hook.

**Comment by ericmann** [comment]
Sorry, a little too ambitious there ... still an issue.

**Comment by ChrisWiegman** [comment]
Saw your first reply. It is definitely something I want to look into soon here. How did the parent project do it?

Chris Wiegman
Senior Web Engineer | 10up
Office: (941) 306-3287 tel:(941)%20306-3287 | Mobile: (808) 250-3287 tel:(808)%20250-3287
http://10up.com http://10up.com/
  https://www.facebook.com/10up.agency      https://twitter.com/10up

**Comment by ericmann** [comment]
The parent project does a delete/re-add on reload as well, which is why we took that approach here.

**Comment by johnpbloch** [comment]
A little late to the convo here, but since I was the one to make that decision when rewriting this code in the first place, I feel I should add my thought process, at the least.

The reason we decided to remove then re-add on either end of a reload was that it seemed most reasonable to always remove hosts when a VM begins to enter an unreachable state (halt, pause, and beginning of reload) and to add them after successfully completing the process of going into a reachable state (up, resume, and the end of a reload). The reason for this is that if the machine is unreachable, the hosts should not be set at all. Once it is reachable, they should be set again. There doesn't seem to be much sense in keeping those hosts set for an address that won't respond.

The reason we decided not to simply refresh on reload is because a reload command can be interrupted without re-entering a reachable state. In such a case, the host names should be removed.

Also, technically speaking, every state change always triggers a removal of all hosts. It's just that any "reachable" state also then triggers the addition of hosts.

@ChrisWiegman I'm more than happy to reconsider the reasoning there with sufficient reason.

> Having hosts automatically refresh on Vagrant reload is somewhat troublesome

How so?

**Comment by ChrisWiegman** [comment]
I almost forgot about this one...

9 times out of 10 (or more) refreshing doesn't involve changing host names. Particularly when switching to this it made for quite a headache. At this point as it's been a while now, I'm pretty much used to it.
